# Generated by Django 5.0.4 on 2024-05-06 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, upload_to='photos/avatar/', verbose_name='Аватар')),
                ('department', models.CharField(max_length=150, verbose_name='Отдел')),
                ('role', models.CharField(max_length=150, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доп. информация о пользоваетеле',
                'verbose_name_plural': ('Доп. информация',),
            },
        ),
    ]
