# Generated by Django 5.0.4 on 2024-05-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Доп. информация о пользоваетеле', 'verbose_name_plural': 'Доп. информация'},
        ),
    ]
