# Generated by Django 5.0.4 on 2024-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='photos/news/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
