# Generated by Django 5.0.4 on 2024-05-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.FileField(upload_to='project/task_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_files',
            field=models.FileField(blank=True, null=True, upload_to='project/update_task_files/%Y/%m/%d/'),
        ),
    ]
