# Generated by Django 5.0.4 on 2024-05-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseTask',
        ),
    ]
