# Generated by Django 5.0.4 on 2024-05-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_options_message_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation_id',
        ),
    ]
