# Generated by Django 5.0.4 on 2024-05-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
