# Generated by Django 5.0.4 on 2024-05-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
